[package]
name = "dsntk-logo"
version = "0.0.2"
authors = ["Dariusz Depta <depta@engos.de>"]
repository = "https://github.com/DecisionToolkit/dsntk-logo.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
domrs = "0.0.16"
