version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  run:
    desc: Generates logo
    cmds:
      - cmd: cargo +stable run

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test

  png:
    desc: Generated PNG images
    cmds:
      - cmd: cargo run
      - cmd: magick -size 700x700 out/decision-contracts-700-07.svg out/decision-contracts-700-07.png
      - cmd: magick -size 300x300 out/decision-contracts-700-07.svg out/decision-contracts-300-07.png
      - cmd: magick -size 700x700 out/decision-contracts-700-09.svg out/decision-contracts-700-09.png
      - cmd: magick -size 300x300 out/decision-contracts-700-09.svg out/decision-contracts-300-09.png
      - cmd: magick -size 700x700 out/decision-tables-700-07.svg out/decision-tables-700-07.png
      - cmd: magick -size 300x300 out/decision-tables-700-07.svg out/decision-tables-300-07.png
      - cmd: magick -size 700x700 out/decision-tables-700-09.svg out/decision-tables-700-09.png
      - cmd: magick -size 300x300 out/decision-tables-700-09.svg out/decision-tables-300-09.png
      - cmd: magick -size 700x700 out/decision-toolkit-700-07.svg out/decision-toolkit-700-07.png
      - cmd: magick -size 300x300 out/decision-toolkit-700-07.svg out/decision-toolkit-300-07.png
      - cmd: magick -size 700x700 out/decision-toolkit-700-09.svg out/decision-toolkit-700-09.png
      - cmd: magick -size 300x300 out/decision-toolkit-700-09.svg out/decision-toolkit-300-09.png
      - cmd: magick -size 700x700 out/decision-dmntk-700-07.svg out/decision-dmntk-700-07.png
      - cmd: magick -size 300x300 out/decision-dmntk-700-07.svg out/decision-dmntk-300-07.png
      - cmd: magick -size 700x700 out/decision-dmntk-700-09.svg out/decision-dmntk-700-09.png
      - cmd: magick -size 300x300 out/decision-dmntk-700-09.svg out/decision-dmntk-300-09.png
      - cmd: magick -size 700x700 out/decision-dsntk-700-07.svg out/decision-dsntk-700-07.png
      - cmd: magick -size 300x300 out/decision-dsntk-700-07.svg out/decision-dsntk-300-07.png
      - cmd: magick -size 700x700 out/decision-dsntk-700-09.svg out/decision-dsntk-700-09.png
      - cmd: magick -size 300x300 out/decision-dsntk-700-09.svg out/decision-dsntk-300-09.png
