version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  run:
    desc: Generate logo in SVG format
    cmds:
      - cmd: cargo +stable run

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test

  out:
    desc: Generates all images from SVG format
    cmds:
      - task: run
      - task: png
      - task: webp

  png:
    desc: Generate PNG images from SVG format
    cmds:
      - cmd: magick -size 700x700 out/blue-700-07.svg out/png/blue-700-07.png
      - cmd: magick -size 300x300 out/blue-700-07.svg out/png/blue-300-07.png
      - cmd: magick -size 700x700 out/blue-700-09.svg out/png/blue-700-09.png
      - cmd: magick -size 300x300 out/blue-700-09.svg out/png/blue-300-09.png
      - cmd: magick -size 700x700 out/green-700-07.svg out/png/green-700-07.png
      - cmd: magick -size 300x300 out/green-700-07.svg out/png/green-300-07.png
      - cmd: magick -size 700x700 out/green-700-09.svg out/png/green-700-09.png
      - cmd: magick -size 300x300 out/green-700-09.svg out/png/green-300-09.png
      - cmd: magick -size 700x700 out/grey-700-07.svg out/png/grey-700-07.png
      - cmd: magick -size 300x300 out/grey-700-07.svg out/png/grey-300-07.png
      - cmd: magick -size 700x700 out/grey-700-09.svg out/png/grey-700-09.png
      - cmd: magick -size 300x300 out/grey-700-09.svg out/png/grey-300-09.png
      - cmd: magick -size 700x700 out/orange-700-07.svg out/png/orange-700-07.png
      - cmd: magick -size 300x300 out/orange-700-07.svg out/png/orange-300-07.png
      - cmd: magick -size 700x700 out/orange-700-09.svg out/png/orange-700-09.png
      - cmd: magick -size 300x300 out/orange-700-09.svg out/png/orange-300-09.png
      - cmd: magick -size 700x700 out/purple-700-07.svg out/png/purple-700-07.png
      - cmd: magick -size 300x300 out/purple-700-07.svg out/png/purple-300-07.png
      - cmd: magick -size 700x700 out/purple-700-09.svg out/png/purple-700-09.png
      - cmd: magick -size 300x300 out/purple-700-09.svg out/png/purple-300-09.png

  webp:
    desc: Generate WebP images from SVG format
    cmds:
      - cmd: magick -size 700x700 out/blue-700-07.svg out/webp/blue-700-07.webp
      - cmd: magick -size 300x300 out/blue-700-07.svg out/webp/blue-300-07.webp
      - cmd: magick -size 700x700 out/blue-700-09.svg out/webp/blue-700-09.webp
      - cmd: magick -size 300x300 out/blue-700-09.svg out/webp/blue-300-09.webp
      - cmd: magick -size 700x700 out/green-700-07.svg out/webp/green-700-07.webp
      - cmd: magick -size 300x300 out/green-700-07.svg out/webp/green-300-07.webp
      - cmd: magick -size 700x700 out/green-700-09.svg out/webp/green-700-09.webp
      - cmd: magick -size 300x300 out/green-700-09.svg out/webp/green-300-09.webp
      - cmd: magick -size 700x700 out/grey-700-07.svg out/webp/grey-700-07.webp
      - cmd: magick -size 300x300 out/grey-700-07.svg out/webp/grey-300-07.webp
      - cmd: magick -size 700x700 out/grey-700-09.svg out/webp/grey-700-09.webp
      - cmd: magick -size 300x300 out/grey-700-09.svg out/webp/grey-300-09.webp
      - cmd: magick -size 700x700 out/orange-700-07.svg out/webp/orange-700-07.webp
      - cmd: magick -size 300x300 out/orange-700-07.svg out/webp/orange-300-07.webp
      - cmd: magick -size 700x700 out/orange-700-09.svg out/webp/orange-700-09.webp
      - cmd: magick -size 300x300 out/orange-700-09.svg out/webp/orange-300-09.webp
      - cmd: magick -size 700x700 out/purple-700-07.svg out/webp/purple-700-07.webp
      - cmd: magick -size 300x300 out/purple-700-07.svg out/webp/purple-300-07.webp
      - cmd: magick -size 700x700 out/purple-700-09.svg out/webp/purple-700-09.webp
      - cmd: magick -size 300x300 out/purple-700-09.svg out/webp/purple-300-09.webp
